### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by puregarlic** [dotmap/knife#3]
There's a number of components that still need to be implemented in the project before we can completely move into feature development:

- [ ] Continuous Integration (most likely on Circle CI)
- [ ] Docker images
- [ ] Testing 
  - [ ] Integration tests (using Cypress)
  - [ ] Unit/Snapshot tests (Luna and snap-shot-it?)
- [ ] License checking (probably Fossa)
- [ ] Security (probably just `npm audit`)
- [ ] Code Quality (codeclimate)
